# Generated by Django 4.0.1 on 2022-01-16 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_of_birth', models.DateField(default=None)),
                ('id_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(0)])),
                ('is_alive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'person_person',
            },
        ),
    ]
