# Generated by Django 4.0.1 on 2022-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
