# Generated by Django 4.0.1 on 2022-01-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_preferred_barber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_alive',
        ),
    ]
