# Generated by Django 4.0.1 on 2022-01-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('person', '0007_alter_person_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preferred_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
