# Generated by Django 4.0.1 on 2022-01-24 17:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('barber', '0001_initial'),
        ('person', '0008_person_preferred_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barber.barber'),
        ),
        migrations.AlterField(
            model_name='person',
            name='preferred_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store'),
        ),
    ]
