# Generated by Django 4.0.1 on 2022-01-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_person_is_active_alter_person_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
